development:
  adapter:   postgresql
  database:  cse-ruet
  username:  cse-ruet
  password:  d872$dh
  host:   localhost
  min_messages: warning

test:
  adapter:   postgresql
  database:  cse-ruet
  username:  cse-ruet
  password:  d872$dh
  host:   localhost
  min_messages: warning

staging:
  adapter:   postgresql
  database:  cse-ruet
  username:  cse-ruet
  password:  d872$dh
  host:   localhost
  min_messages: warning

production:
  adapter:   postgresql
  database:  cse-ruet
  username:  cse-ruet
  password:  d872$dh
 
